export enum RTC_CALL_API_EVENTS {
    CALL_JOINED = 'CALL_JOINED',
    PARTICIPANT_JOINED = 'PARTICIPANT_JOINED',
    PARTICIPANT_LEFT = 'PARTICIPANT_LEFT',
    CALL_LEFT = 'CALL_LEFT',
    CALL_ENDED = 'CALL_ENDED'
}

export enum RTC_CALL_COMMANDS {
    JOIN_CALL = 'JOIN_CALL',
    END_CALL = 'END_CALL',
    TOGGLE_MIC = 'TOGGLE_MIC',
    TOGGLE_CAM = 'TOGGLE_CAM',
    SET_AVATAR = 'SET_AVATAR',
    SET_DISPLAY_NAME = 'SET_DISPLAY_NAME',
    SET_TITLE = 'SET_TITLE',
    SET_SUBTITLE = 'SET_SUBTITLE'
}
export enum RTC_CALL_FUNCTIONS {
    GET_CALL_INFO = 'GET_CALL_INFO',
    GET_PARTICIPANT_INFO = 'GET_PARTICIPANT_INFO',
    GET_PARTICIPANT_AVATAR_URL = 'GET_PARTICIPANT_AVATAR_URL'
}         